routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Home\HomeController@index')->name('home');

Route::group(['prefix' => 'auth', 'as' => 'auth.'], function () {
  Route::get('/signin', 'Auth\AuthController@signin')->name('signin');
  Route::get('/signup', 'Auth\AuthController@signup')->name('signup');
  Route::post('/signin', 'Auth\LoginController@authenticate')->name('authenticate');
  Route::post('/signup', 'Auth\RegisterController@register')->name('register');
  Route::get('/logout', 'Auth\LogoutController@logout')->name('logout');
});

Route::group(['prefix' => 'streets', 'as' => 'streets.'], function () {
  Route::get('/{id?}', 'Home\HomeController@streetDetail')->name('show');
});

Route::group(['prefix' => 'bridges', 'as' => 'bridges.'], function () {
  Route::get('/{id?}', 'Home\HomeController@bridgeDetail')->name('show');
});

// Route::get('/login', 'Auth\AuthController@login')->name('login');
// Route::get('/register', 'Auth\AuthController@register')->name('register');
// Route::get('/profile', 'Auth\AuthController@profile')->name('profile');

Route::group([
  'prefix' => 'p',
  'as' => 'admin.',
  // 'middleware' => ['auth']
], function () {

  Route::get('/', 'Dashboard\DashboardController@index')->name('dashboard');

  Route::group(['prefix' => 'streets', 'as' => 'streets.'], function () {
    Route::get('/', 'Street\StreetController@list')->name('list');
    Route::get('/create', 'Street\StreetController@create')->name('create');
    Route::post('/destroy/{id?}', 'Street\StreetController@destroy')->name('destroy');
    Route::post('/', 'Street\StreetController@new')->name('new');

    Route::group(['prefix' => '{id}'], function () {
      Route::get('/', 'Street\StreetController@edit')->name('edit');
      Route::post('/', 'Street\StreetController@update')->name('update');
      Route::post('/avatar', 'Street\StreetController@setAvatar')->name('setAvatar');
      Route::post('/cover', 'Street\StreetController@setCover')->name('setCover');

      Route::group(['prefix' => 'bridges', 'as' => 'bridges.'], function () {
        Route::get('/', 'Street\StreetController@bridgeList')->name('list');
      });

      Route::group(['prefix' => 'conditions', 'as' => 'conditions.'], function () {
        Route::get('/', 'Street\StreetController@conditionList')->name('list');
        Route::post('/', 'Street\StreetController@newCondition')->name('new');
        Route::post('/{conditionId}', 'Street\StreetController@updateCondition')->name('update');
      });

      Route::group(['prefix' => 'technicals', 'as' => 'technicals.'], function () {
        Route::get('/', 'Street\StreetController@technicalList')->name('list');
        Route::post('/', 'Street\StreetController@newTechnical')->name('new');
        Route::post('/{technicalId}', 'Street\StreetController@updateTechnical')->name('update');
      });

      Route::group(['prefix' => 'images', 'as' => 'images.'], function () {
        Route::get('/', 'Street\StreetController@imageList')->name('list');
        Route::post('/', 'Street\StreetController@newImage')->name('new');
        Route::post('/{imageId}', 'Street\StreetController@updateImage')->name('update');
      });

      Route::group(['prefix' => 'videos', 'as' => 'videos.'], function () {
        Route::get('/', 'Street\StreetController@videoList')->name('list');
        Route::post('/', 'Street\StreetController@newVideo')->name('new');
        // Route::post('/{videoId}', 'Street\StreetController@updateVideo')->name('update');
        Route::post('/destroy/{videoId?}', 'Street\StreetController@destroyStreetVideo')->name('destroy');
      });
    });
  });

  Route::group(['prefix' => 'conditions', 'as' => 'conditions.'], function () {
    Route::post('/destroy/{id?}', 'Condition\ConditionController@destroy')->name('destroy');
  });

  Route::group(['prefix' => 'technicals', 'as' => 'technicals.'], function () {
    Route::post('/destroy/{id?}', 'Technical\TechnicalController@destroy')->name('destroy');
  });

  Route::group(['prefix' => 'details', 'as' => 'details.'], function () {
    Route::post('/destroy/{id?}', 'BridgeDetail\BridgeDetailController@destroy')->name('destroy');
  });

  Route::group(['prefix' => 'bridges', 'as' => 'bridges.'], function () {
    Route::get('/', 'Bridge\BridgeController@list')->name('list');
    Route::get('/create', 'Bridge\BridgeController@create')->name('create');
    Route::post('/save', 'Bridge\BridgeController@store')->name('store');
    Route::post('/destroy/{id?}', 'Bridge\BridgeController@destroy')->name('destroy');

    Route::group(['prefix' => '{id}'], function () {
      Route::get('/', 'Bridge\BridgeController@edit')->name('edit');
      Route::post('/', 'Bridge\BridgeController@store')->name('update');

      Route::group(['prefix' => 'details', 'as' => 'details.'], function () {
        Route::get('/', 'Bridge\BridgeController@detailList')->name('list');
        Route::post('/', 'Bridge\BridgeController@newDetail')->name('new');
        Route::post('/{detailId}', 'Bridge\BridgeController@updateDetail')->name('update');
      });

      Route::group(['prefix' => 'images', 'as' => 'images.'], function () {
        Route::get('/', 'Bridge\BridgeController@imageList')->name('list');
        Route::post('/', 'Bridge\BridgeController@newImage')->name('new');
        Route::post('/{imageId}', 'Bridge\BridgeController@updateImage')->name('update');
      });
    });
  });

  Route::group(['prefix' => 'images', 'as' => 'images.'], function () {
    Route::post('/{id?}', 'Image\ImageController@update')->name('update');
    Route::post('/destroy/{id?}', 'Image\ImageController@destroy')->name('destroy');
  });

});

app/Street.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Street extends Model
{
    // Street condition relationship
    public function conditions()
    {
        return $this->hasMany('App\Condition');
    }

    // Street condition relationship
    public function technicals()
    {
        return $this->hasMany('App\Technical');
    }

    public function village()
    {
        return $this->belongsTo('Laravolt\Indonesia\Models\Village', 'kelurahan_id');
    }

    public function district()
    {
        return $this->belongsTo('Laravolt\Indonesia\Models\District', 'kecamatan_id');
    }

    public function images()
    {
        return $this->hasMany('App\Image');
    }

    public function avatar()
    {
        return $this->belongsTo('App\Image', 'avatar_id');
    }

    public function cover()
    {
        return $this->belongsTo('App\Image', 'cover_id');
    }

    public function bridges()
    {
        return $this->hasMany('App\Bridge');
    }

    public function videos()
    {
        return $this->hasMany('App\StreetVideo');
    }

    protected $fillable = [
        'name',
        'section_number',
        'base_section_name',
        'end_section_name',
        'validity_year',
        'polyline',
        'base_section_latitude',
        'base_section_longitude',
        'end_section_latitude',
        'end_section_longitude',
        'google_base_street_name',
        'google_end_street_name',
        'google_middle_street_name',
    ];
}

app/StreetType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class StreetType extends Model
{
    public function details()
    {
        return $this->hasMany('App\detail');
    }
}

app/Http/Controllers/Street/StreetController.php
<?php

namespace App\Http\Controllers\Street;

use App\Http\Controllers\Controller;
use App\Street;
use App\Condition;
use App\Technical;
use App\Image;
use App\StreetVideo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Hash;
use Indonesia;
use Cocur\Slugify\Slugify;
use InterventionImage;

class StreetController extends Controller
{
  /**
   * Street list view controller
   *
   * @param Request $request Application request
   * @return view
   * @throws null
   **/
  public function list(Request $request)
  {
    $query = $request->input('query');
    $take = config('app.pagination.street.take');
    $streets = Street::with('village', 'village.district', 'village.district.city');
    if (! empty($query)) {
      $streets = $streets->where('name', 'like', sprintf('%%%s%%', $query))
                        ->orWhere('section_number', 'like', sprintf('%%%s%%', $query))
                        ->orWhere('base_section_name', 'like', sprintf('%%%s%%', $query))
                        ->orWhere('end_section_name', 'like', sprintf('%%%s%%', $query));
    }
    $streets = $streets->paginate($take);

    if ($request->ajax()) {
      return View::make('street.table-records', compact('streets', 'query'));
    }

    return view('street.list', compact('streets', 'query'));
  }

  /**
   * Street list view controller
   *
   * @param Request $request Application request
   * @return view
   * @throws null
   **/
  public function create(Request $request)
  {
    $kabupaten = Indonesia::findProvince(51, ['cities']);

    return view('street.create', compact('kabupaten'));
  }

  /**
   * Street list view controller
   *
   * @param Request $request Application request
   * @return view
   * @throws null
   **/
  public function edit(Request $request, $id)
  {
    $kabupaten = Indonesia::findProvince(51, ['cities']);
    $street = Street::find($id);
    $street->base_coordinate_section = sprintf('%s,%s', $street->base_section_latitude, $street->base_section_longitude);
    $street->end_coordinate_section = sprintf('%s,%s', $street->end_section_latitude, $street->end_section_longitude);

    $path = [];
    $rawCoordinates = explode(';', $street->polyline);
    foreach ($rawCoordinates as $key => $coordinate) {
      $explodedCoordinate = explode(',', $coordinate);
      array_push($path, (object)[
        'lat' => (float)$explodedCoordinate[0],
        'lng' => (float)$explodedCoordinate[1],
      ]);
    }
    $street->polyline = json_encode($path);

    return view('street.edit', compact('kabupaten', 'street'));
  }

  /**
   * Street new street controller
   *
   * @param Request $request Application request
   * @return redirect
   * @throws null
   **/
  public function new(Request $request)
  {
    $baseSectionCoordinate = explode(',', $request->input('base_coordinate_section', ''));
    $endSectionCoordinate = explode(',', $request->input('end_coordinate_section', ''));

    $street = new Street;
    $street->name = $request->input('name');
    $street->section_number = $request->input('number');
    $street->base_section_name = $request->input('base_section_name');
    $street->end_section_name = $request->input('end_section_name');
    $street->kabupaten_id = config('app.kabupaten');
    $street->kecamatan_id = $request->input('kecamatan');
    $street->kelurahan_id = $request->input('kelurahan');
    $street->base_section_latitude = $baseSectionCoordinate[0];
    $street->base_section_longitude = $baseSectionCoordinate[1];
    $street->end_section_latitude = $endSectionCoordinate[0];
    $street->end_section_longitude = $endSectionCoordinate[1];
    $street->polyline = $request->input('polyline');
    $street->google_base_street_name = $request->input('google_base_street_name');
    $street->google_end_street_name = $request->input('google_end_street_name');
    $street->google_middle_street_name = $request->input('google_middle_street_name');

    $street->save();
    
    return redirect()->route('admin.streets.list');
  }

  /**
   * Street new street controller
   *
   * @param Request $request Application request
   * @return redirect
   * @throws null
   **/
  public function update(Request $request, $id)
  {
    $baseSectionCoordinate = explode(',', $request->input('base_coordinate_section', ''));
    $endSectionCoordinate = explode(',', $request->input('end_coordinate_section', ''));

    $street = Street::find($id);
    $street->name = $request->input('name');
    $street->section_number = $request->input('number');
    $street->base_section_name = $request->input('base_section_name');
    $street->end_section_name = $request->input('end_section_name');
    $street->kabupaten_id = config('app.kabupaten');
    $street->kecamatan_id = $request->input('kecamatan');
    $street->kelurahan_id = $request->input('kelurahan');
    $street->base_section_latitude = $baseSectionCoordinate[0];
    $street->base_section_longitude = $baseSectionCoordinate[1];
    $street->end_section_latitude = $endSectionCoordinate[0];
    $street->end_section_longitude = $endSectionCoordinate[1];
    $street->polyline = $request->input('polyline');
    $street->google_base_street_name = $request->input('google_base_street_name');
    $street->google_end_street_name = $request->input('google_end_street_name');
    $street->google_middle_street_name = $request->input('google_middle_street_name');

    $street->save();
    
    return redirect()->route('admin.streets.list');
  }

  // Home controller to view the home page
  public function search(Request $request)
  {
    $query = $request->input('name');
    $streets = Street::where('name', 'like', sprintf('%%%s%%', $query))
                        ->orWhere('section_number', 'like', sprintf('%%%s%%', $query))
                        ->orWhere('base_section_name', 'like', sprintf('%%%s%%', $query))
                        ->orWhere('end_section_name', 'like', sprintf('%%%s%%', $query))
                        ->orWhere('google_base_street_name', 'like', sprintf('%%%s%%', $query))
                        ->orWhere('google_end_street_name', 'like', sprintf('%%%s%%', $query))
                        ->orWhere('google_middle_street_name', 'like', sprintf('%%%s%%', $query))
                        ->get();

    $data = [
      'view' => View::make('_partials.result', compact('streets', 'query'))
    ];

    return $data['view'];
  }

  public function all(Request $request)
  {
    $districtId = $request->input('kecamatan', null);
    if (! empty($districtId)) {
      $streets = Street::where('kecamatan_id', '=', $districtId)->get();
    } else {
      $streets = Street::all();
    }
    $mappedStreets = $streets->map(function($street) {
      $path = [];
      $rawCoordinates = explode(';', $street->polyline);
      foreach ($rawCoordinates as $key => $coordinate) {
        $explodedCoordinate = explode(',', $coordinate);
        array_push($path, (object)[
          'latitude' => (float)$explodedCoordinate[0],
          'longitude' => (float)$explodedCoordinate[1],
        ]);
      }
      return (object)[
        'id' => $street->id,
        'name' => $street->name,
        'path' => $path,
      ];
    });
    return response()->json($mappedStreets);
  }

  public function detail(Request $request, $id)
  {
    $street = Street::find($id);

    $data = [
      'view' => View::make('_partials.detail', compact('street'))
    ];

    return $data['view'];
    return response()->json($street);
  }

  public function destroy(Request $request, $id)
  {
    try {
      $street = Street::find($id);
      $street->delete();
    } catch (Exception $e) {
      return $e->getMessage();
    }

    return response()->json($street);
  }

  public function bridgeList(Request $request, $id)
  {
    $street = Street::find($id);

    $path = [];
    $rawCoordinates = explode(';', $street->polyline);
    foreach ($rawCoordinates as $key => $coordinate) {
      $explodedCoordinate = explode(',', $coordinate);
      array_push($path, (object)[
        'lat' => (float)$explodedCoordinate[0],
        'lng' => (float)$explodedCoordinate[1],
      ]);
    }
    $street->polyline = json_encode($path);

    return view('street.bridges', compact('street'));
  }

  public function conditionList(Request $request, $id)
  {
    $currentYear = date('Y');
    $selectedYear = $request->input('year', $currentYear);
    $currentCondition = null;

    $take = config('app.pagination.street.take');
    $street = Street::find($id);
    $rawConditions = $street->conditions();

    if (! empty($selectedYear)) {
      $currentCondition = Condition::where([
        ['street_id', '=', $id],
        ['year', '=', $selectedYear],
      ])->first();
    }

    $conditions = $rawConditions->paginate($take);
    $years = [];
    for ($year = $currentYear + 2 ; $year > $currentYear - 8; $year--) { 
      array_push($years, $year);
    }

    $vars = compact('street', 'conditions', 'years', 'selectedYear', 'currentCondition');

    return view('street.conditions', $vars);
  }

  public function technicalList(Request $request, $id)
  {
    $currentYear = date('Y');
    $selectedYear = $request->input('year', $currentYear);
    $currentTechnical = null;

    $take = config('app.pagination.street.take');
    $street = Street::find($id);
    $rawTechnicals = $street->technicals();

    if (! empty($selectedYear)) {
      $currentTechnical = Technical::where([
        ['street_id', '=', $id],
        ['year', '=', $selectedYear],
      ])->first();
    }

    $technicals = $rawTechnicals->paginate($take);
    $years = [];
    for ($year = $currentYear + 2 ; $year > $currentYear - 8; $year--) { 
      array_push($years, $year);
    }

    $vars = compact('street', 'technicals', 'years', 'selectedYear', 'currentTechnical');

    return view('street.technicals', $vars);
  }

  public function newCondition(Request $request)
  {

resources/views/street/images.blade.php
@extends('layouts.dashboard.main')

@section('title')
<h1>
  @lang('street.manage_gallery')
  <small>{{ $street->name }}</small>
</h1>
@stop

@section('content')
<div class="box box-primary">

  <div class="box-header with-border">
    <div class="row">
      <div class="col-xs-12">
        <div class="btn-group">
          <a href="{{ route('admin.streets.list') }}" class="btn btn-danger">
            <i class="fas fa-arrow-left"></i><span class="hidden-xs"> @lang('street.see_all')</span>
          </a>
          <a href="{{ route('admin.streets.edit', ['id' => $street->id]) }}" type="button" class="btn btn-default">
            <i class="fas fa-edit"></i><span class="hidden-xs"> @lang('street.edit')</span>
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="box-body">
    <div class="row">
      <div class="col-xs-12 col-md-5 col-lg-4 image-form-container">
        <form id="fileupload" action="{{ route('admin.streets.images.new', ['id' => $street->id]) }}" method="POST" enctype="multipart/form-data">
          <div class="row fileupload-buttonbar">
            <div class="col-xs-12">
              <div class="btn-group">
                <button type="button" class="btn btn-success fileinput-button">
                  <i class="fas fa-plus"></i>
                  <span class="hidden-xs">@lang('gallery.add_files')</span>
                  <input type="file" name="files[]" multiple>
                </button>
                <button type="submit" class="btn btn-primary start">
                  <i class="fas fa-upload"></i>
                  <span class="hidden-xs">@lang('gallery.start_upload')</span>
                </button>
              </div>
            </div>
            <div class="col-xs-12">
              <span class="fileupload-process"></span>
            </div>
            <div class="col-xs-12 fileupload-progress fade">
              <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                  <div class="progress-bar progress-bar-success" style="width:0%;"></div>
              </div>
              <div class="progress-extended">&nbsp;</div>
            </div>
          </div>
          <div class="box box-primary">
            <div class="box-body table-responsive">
              <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
            </div>
          </div>
        </form>

      </div>
      <div class="col-xs-12 col-md-7 col-lg-8 image-container">
        @if ($images->count() > 0)

        @foreach ($images as $image)
          <div class="image-item-container">
            <div class="image-box">
              <img class="contain" src="{{ asset('storage/' . $image->filename) }}" alt="{{ $image->name }}">
            </div>
            <div class="image-title-container">
              <h4 class="image-title">{{ $image->name }}</h4>
            </div>
            <div class="action-container">
              <div class="btn-group">
                <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                  <i class="fas fa-cog"></i>
                </button>
                <ul class="dropdown-menu dropdown-menu-right">
                  @if ($street->avatar_id != $image->id)
                  <li>
                    <a href="#" class="use-avatar" data-id="{{ $image->id }}"><i class="fas fa-image"></i> @lang('gallery.use_as_avatar')</a>
                  </li>
                  @endif
                  @if ($street->cover_id != $image->id)
                  <li>
                    <a href="#" class="use-cover" data-id="{{ $image->id }}"><i class="fas fa-image"></i> @lang('gallery.use_as_cover')</a>
                  </li>
                  @endif
                  <li class="divider"></li>
                  <li>
                    <a href="#" class="update-name" data-id="{{ $image->id }}" data-title="{{ $image->name }}"><i class="fas fa-edit"></i> @lang('gallery.edit')</a>
                  </li>
                  <li>
                    <a href="#" class="delete-image" data-id="{{ $image->id }}"><i class="fas fa-trash"></i> @lang('gallery.delete')</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        @endforeach

        @else
        <p class="text-muted">
          @lang('gallery.empty')
        </p>
        @endif
        @if ($images->lastPage() > 1)
        <div class="box-footer clearfix">
          {{ $images->appends(['query' => Request::get('query')])->links('vendor.pagination.default') }}
        </div>
        @endif
      </div>
    </div>
  </div>
</div> 
@stop

@section('customScripts')

<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td>
      <span class="preview"></span>
    </td>
    <td>
      <p class="name">{%=file.name%}</p>
      <strong class="error text-danger"></strong>
    </td>
    <td>
      <p class="size">@lang('gallery.processing')</p>
      <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
    </td>
    <td>
      {% if (!i && !o.options.autoUpload) { %}
        <button class="btn btn-xs btn-primary start" disabled>
          <i class="fas fa-upload"></i>
          <span>@lang('gallery.upload')</span>
        </button>
      {% } %}
    </td>
  </tr>
{% } %}
</script>

<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-download fade">
    <td>
      <span class="preview">
        {% if (file.thumbnailUrl) { %}
          <a href="#" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.filename%}"></a>
        {% } %}
      </span>
    </td>
    <td>
      <p class="name">
        <span>{%=file.name%}</span>
      </p>
      {% if (file.error) { %}
        <div><span class="label label-danger">Error</span> {%=file.error%}</div>
      {% } %}
    </td>
    <td>
      <span class="size">{%=o.formatFileSize(file.size)%}</span>
    </td>
  </tr>
{% } %}
</script>

<script src="{{ asset('vendor/jquery-file-upload/js/vendor/jquery.ui.widget.js') }}"></script>
<script src="https://blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script>
<script src="https://blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>
<script src="{{ asset('vendor/jquery-file-upload/js/jquery.iframe-transport.js') }}"></script>
<script src="{{ asset('vendor/jquery-file-upload/js/jquery.fileupload.js') }}"></script>
<script src="{{ asset('vendor/jquery-file-upload/js/jquery.fileupload-process.js') }}"></script>
<script src="{{ asset('vendor/jquery-file-upload/js/jquery.fileupload-image.js') }}"></script>
<script src="{{ asset('vendor/jquery-file-upload/js/jquery.fileupload-validate.js') }}"></script>
<script src="{{ asset('vendor/jquery-file-upload/js/jquery.fileupload-ui.js') }}"></script>

<script>
$(function () {

  $('#fileupload').fileupload({
    dataType: 'json',
    url: '{{ route('admin.streets.images.new', ['id' => $street->id]) }}',
    progressall: function (e, data) {
      var progress = parseInt(data.loaded / data.total * 100, 10);
      if (progress >= 100) {
        setTimeout(function () {
          window.location.reload();
        }, 1000);
      }
    }
  });

  $('.image-container').on('click', '.delete-image', function(event) {
    event.preventDefault();
    var imageId = $(this).data('id');
    var recordEl = $(this).closest('tr');
    $.confirm({
      title: '@lang('street.delete_confirmation_title')',
      content: '@lang('street.delete_confirmation_content')',
      buttons: {
        confirm: function () {
          $.ajax({
            url: '{{ route('admin.images.destroy') }}/' + imageId,
            method: 'POST',
            dataType: 'json',
          }).done(function(response) {
            window.location.reload(true);
          });
        },
        cancel: function () {
        }
      }
    });
  });

  $('.image-container').on('click', '.update-name', function(event) {
    event.preventDefault();
    var imageId = $(this).data('id');
    var recordEl = $(this).closest('tr');
    var imageTitle = $(this).data('title');
    $.confirm({
      title: '@lang('gallery.edit')',
      content: '' +
      '<form action="" class="formName">' +
      '<div class="form-group">' +
      '<input type="text" placeholder="@lang('gallery.name')" class="name form-control" value="' + imageTitle + '" required />' +
      '</div>' +
      '</form>',
      buttons: {
        formSubmit: {
          text: 'Submit',
          btnClass: 'btn-blue',
          action: function () {
            var name = this.$content.find('.name').val();
            if(!name){
              $.alert('@lang('gallery.validate.name')');
              return false;
            }
            $.ajax({
              url: '{{ route('admin.images.update') }}/' + imageId,
              method: 'POST',
              dataType: 'json',
              data: {
                'name': name
              }
            }).done(function(response) {
              window.location.reload(true);
            });
          }
        },
        cancel: function () {
            //close
        },
      },
      onContentReady: function () {
        // bind to events
        var jc = this;
        this.$content.find('form').on('submit', function (e) {
          // if the user submits the form by pressing enter in the field.
          e.preventDefault();
          jc.$$formSubmit.trigger('click'); // reference the button and click it
        });
      }
    });

  });

  $('.image-container').on('click', '.use-avatar', function(event) {
    event.preventDefault();
    var imageId = $(this).data('id');
    var recordEl = $(this).closest('tr');
    $.confirm({
      title: '@lang('gallery.avatar_confirmation_title')',
      content: '@lang('gallery.avatar_confirmation_content')',
      buttons: {
        confirm: function () {
          $.ajax({
            url: '{{ route('admin.streets.setAvatar', ['id' => $street->id]) }}',
            method: 'POST',
            dataType: 'json',
            data: {
              'imageId': imageId
            }
          }).done(function(response) {
            window.location.reload(true);
          });
        },
        cancel: function () {
        }
      }
    });
  });

  $('.image-container').on('click', '.use-cover', function(event) {
    event.preventDefault();
    var imageId = $(this).data('id');
    var recordEl = $(this).closest('tr');
    $.confirm({
      title: '@lang('gallery.cover_confirmation_title')',
      content: '@lang('gallery.cover_confirmation_content')',
      buttons: {
        confirm: function () {
          $.ajax({
            url: '{{ route('admin.streets.setCover', ['id' => $street->id]) }}',
            method: 'POST',
            dataType: 'json',
            data: {
              'imageId': imageId
            }
          }).done(function(response) {
            window.location.reload(true);
          });
        },
        cancel: function () {
        }
      }
    });
  });

});
</script>
@stop