routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Home\HomeController@index')->name('home');

Route::group(['prefix' => 'auth', 'as' => 'auth.'], function () {
  Route::get('/signin', 'Auth\AuthController@signin')->name('signin');
  Route::get('/signup', 'Auth\AuthController@signup')->name('signup');
  Route::post('/signin', 'Auth\LoginController@authenticate')->name('authenticate');
  Route::post('/signup', 'Auth\RegisterController@register')->name('register');
  Route::get('/logout', 'Auth\LogoutController@logout')->name('logout');
});

Route::group(['prefix' => 'streets', 'as' => 'streets.'], function () {
  Route::get('/{id?}', 'Home\HomeController@streetDetail')->name('show');
});

Route::group(['prefix' => 'bridges', 'as' => 'bridges.'], function () {
  Route::get('/{id?}', 'Home\HomeController@bridgeDetail')->name('show');
});

// Route::get('/login', 'Auth\AuthController@login')->name('login');
// Route::get('/register', 'Auth\AuthController@register')->name('register');
// Route::get('/profile', 'Auth\AuthController@profile')->name('profile');

Route::group([
  'prefix' => 'p',
  'as' => 'admin.',
  // 'middleware' => ['auth']
], function () {

  Route::get('/', 'Dashboard\DashboardController@index')->name('dashboard');

  Route::group(['prefix' => 'streets', 'as' => 'streets.'], function () {
    Route::get('/', 'Street\StreetController@list')->name('list');
    Route::get('/create', 'Street\StreetController@create')->name('create');
    Route::post('/destroy/{id?}', 'Street\StreetController@destroy')->name('destroy');
    Route::post('/', 'Street\StreetController@new')->name('new');

    Route::group(['prefix' => '{id}'], function () {
      Route::get('/', 'Street\StreetController@edit')->name('edit');
      Route::post('/', 'Street\StreetController@update')->name('update');
      Route::post('/avatar', 'Street\StreetController@setAvatar')->name('setAvatar');
      Route::post('/cover', 'Street\StreetController@setCover')->name('setCover');

      Route::group(['prefix' => 'bridges', 'as' => 'bridges.'], function () {
        Route::get('/', 'Street\StreetController@bridgeList')->name('list');
      });

      Route::group(['prefix' => 'conditions', 'as' => 'conditions.'], function () {
        Route::get('/', 'Street\StreetController@conditionList')->name('list');
        Route::post('/', 'Street\StreetController@newCondition')->name('new');
        Route::post('/{conditionId}', 'Street\StreetController@updateCondition')->name('update');
      });

      Route::group(['prefix' => 'technicals', 'as' => 'technicals.'], function () {
        Route::get('/', 'Street\StreetController@technicalList')->name('list');
        Route::post('/', 'Street\StreetController@newTechnical')->name('new');
        Route::post('/{technicalId}', 'Street\StreetController@updateTechnical')->name('update');
      });

      Route::group(['prefix' => 'images', 'as' => 'images.'], function () {
        Route::get('/', 'Street\StreetController@imageList')->name('list');
        Route::post('/', 'Street\StreetController@newImage')->name('new');
        Route::post('/{imageId}', 'Street\StreetController@updateImage')->name('update');
      });

      Route::group(['prefix' => 'videos', 'as' => 'videos.'], function () {
        Route::get('/', 'Street\StreetController@videoList')->name('list');
        Route::post('/', 'Street\StreetController@newVideo')->name('new');
        // Route::post('/{videoId}', 'Street\StreetController@updateVideo')->name('update');
        Route::post('/destroy/{videoId?}', 'Street\StreetController@destroyStreetVideo')->name('destroy');
      });
    });
  });

  Route::group(['prefix' => 'conditions', 'as' => 'conditions.'], function () {
    Route::post('/destroy/{id?}', 'Condition\ConditionController@destroy')->name('destroy');
  });

  Route::group(['prefix' => 'technicals', 'as' => 'technicals.'], function () {
    Route::post('/destroy/{id?}', 'Technical\TechnicalController@destroy')->name('destroy');
  });

  Route::group(['prefix' => 'details', 'as' => 'details.'], function () {
    Route::post('/destroy/{id?}', 'BridgeDetail\BridgeDetailController@destroy')->name('destroy');
  });

  Route::group(['prefix' => 'bridges', 'as' => 'bridges.'], function () {
    Route::get('/', 'Bridge\BridgeController@list')->name('list');
    Route::get('/create', 'Bridge\BridgeController@create')->name('create');
    Route::post('/save', 'Bridge\BridgeController@store')->name('store');
    Route::post('/destroy/{id?}', 'Bridge\BridgeController@destroy')->name('destroy');

    Route::group(['prefix' => '{id}'], function () {
      Route::get('/', 'Bridge\BridgeController@edit')->name('edit');
      Route::post('/', 'Bridge\BridgeController@store')->name('update');

      Route::group(['prefix' => 'details', 'as' => 'details.'], function () {
        Route::get('/', 'Bridge\BridgeController@detailList')->name('list');
        Route::post('/', 'Bridge\BridgeController@newDetail')->name('new');
        Route::post('/{detailId}', 'Bridge\BridgeController@updateDetail')->name('update');
      });

      Route::group(['prefix' => 'images', 'as' => 'images.'], function () {
        Route::get('/', 'Bridge\BridgeController@imageList')->name('list');
        Route::post('/', 'Bridge\BridgeController@newImage')->name('new');
        Route::post('/{imageId}', 'Bridge\BridgeController@updateImage')->name('update');
      });
    });
  });

  Route::group(['prefix' => 'images', 'as' => 'images.'], function () {
    Route::post('/{id?}', 'Image\ImageController@update')->name('update');
    Route::post('/destroy/{id?}', 'Image\ImageController@destroy')->name('destroy');
  });

});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">

    <title>Bina Marga Street Management - @yield('title', 'Home Page')</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,700" rel="stylesheet">

    <link href="/css/vendor.css" rel="stylesheet" type="text/css" />
    <link href="/vendor/jquery-confirm/jquery-confirm.min.css" rel="stylesheet" type="text/css" />
    <link href="/vendor/lightbox/css/lightbox.min.css" rel="stylesheet" type="text/css" />
    <link href="/css/app.css" rel="stylesheet" type="text/css" />

  </head>
  <body class="font-sans">
    @include('layouts.header')
    <div class="application-container">
      @yield('content')
    </div>
    @include('layouts.footer')

    @include('layouts.auth')
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="/vendor/lodash/lodash.min.js"></script>
    <script src="/vendor/jquery-confirm/jquery-confirm.min.js"></script>
    <script src="/vendor/micromodal/micromodal.min.js"></script>
    <script src="/vendor/lightbox/js/lightbox.min.js"></script>
    <script src="/js/app.js" type="javascript"></script>
    <script src="/js/auth.js"></script>
    @yield('customScripts')
  </body>
</html>

resources/views/layouts/auth.blade.php
<div class="modal micromodal-slide" id="modal-auth" aria-hidden="true">
  <div class="modal__overlay p-4" tabindex="-1" data-custom-close>
    <div class="modal__container w-full max-w-xs modal-auth" role="dialog" aria-modal="true" aria-labelledby="modal-2-title">
      <header class="modal__header">
        <button class="modal__close" aria-label="Close modal" data-custom-close></button>
      </header>
      <div class="w-full">

        <div class="login-container">
          <h3 class="modal__title text-red font-bold">
            🔒 @lang('auth.signin')
          </h3>
          <form class="pt-5 mb-4" role="form" action="{{ route('auth.authenticate') }}" method="POST">
            {{ csrf_field() }}
            <div class="mb-4">
              <label class="block text-grey-darker text-sm font-bold mb-2" for="username">
                @lang('auth.username')
              </label>
              <input class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" type="text" placeholder="@lang('auth.username')" name="username">
              <p class="text-red text-xs italic mt-3 hidden">@lang('auth.username_help')</p>
            </div>
            <div class="mb-6">
              <label class="block text-grey-darker text-sm font-bold mb-2" for="password">
                @lang('auth.password')
              </label>
              <input class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" type="password" placeholder="•••••••" name="password">
              <p class="text-red text-xs italic mt-3 hidden">@lang('auth.password_help')</p>
            </div>
            <div class="flex items-center justify-between">
              <button class="bg-blue hover:bg-blue-dark text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                @lang('auth.signin')
              </button>
              <a class="inline-block align-baseline font-bold text-sm text-blue hover:text-blue-darker signup" href="#">
                @lang('auth.signup')
              </a>
            </div>
          </form>
        </div>

        <div class="signup-container">
          <h3 class="modal__title text-red font-bold">
            🔏 @lang('auth.signup')
          </h3>
          <form class="pt-5 mb-4" role="form" action="{{ route('auth.register') }}" method="POST">
            {{ csrf_field() }}
            <div class="mb-4">
              <label class="block text-grey-darker text-sm font-bold mb-2" for="name">
                @lang('auth.name')
              </label>
              <input class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" type="text" placeholder="@lang('auth.name')" name="name">
              <p class="text-red text-xs italic mt-3 hidden">@lang('auth.name_help')</p>
            </div>

            <div class="mb-4">
              <label class="block text-grey-darker text-sm font-bold mb-2" for="username">
                @lang('auth.username')
              </label>
              <input class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" type="text" placeholder="@lang('auth.username')" name="username">
              <p class="text-red text-xs italic mt-3 hidden">@lang('auth.username_help')</p>
            </div>

            <div class="mb-4">
              <label class="block text-grey-darker text-sm font-bold mb-2" for="email">
                @lang('auth.email')
              </label>
              <input class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" type="text" placeholder="@lang('auth.email')" name="email">
              <p class="text-red text-xs italic mt-3 hidden">@lang('auth.email_email')</p>
            </div>

            <div class="mb-4">
              <label class="block text-grey-darker text-sm font-bold mb-2" for="password">
                @lang('auth.password')
              </label>
              <input class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" type="password" placeholder="•••••••" name="password">
              <p class="text-red text-xs italic mt-3 hidden">@lang('auth.password_help')</p>
            </div>

            <div class="mb-6">
              <label class="block text-grey-darker text-sm font-bold mb-2" for="password_confirmation">
                @lang('auth.password_confirmation')
              </label>
              <input class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" type="password" placeholder="•••••••" name="password_confirmation">
              <p class="text-red text-xs italic mt-3 hidden">@lang('auth.password_confirmation_help')</p>
            </div>

            <div class="flex items-center justify-between">
              <button class="bg-blue hover:bg-blue-dark text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                @lang('auth.signup')
              </button>
              <a class="inline-block align-baseline font-bold text-sm text-blue hover:text-blue-darker signin" href="#">
                @lang('auth.already_signup')
              </a>
            </div>
          </form>
        </div>
        
      </div>
    </div>
  </div>
</div>

resources/views/layouts/footer.blade.php
<div class="footer">
</div>

resources/views/layouts/header.blade.php
<nav class="flex items-center justify-between flex-wrap bg-red p-4">

  <div class="md:items-center md:flex-no-shrink text-white mr-6 md:flex">
    <a href="{{ route('home') }}" class="text-white">
      <span class="font-semibold text-base md:text-xl tracking-tight mr-0 md:mr-2">
        <i class="fas fa-map-marker-alt"></i>
      </span>
      <span class="font-semibold text-xl tracking-tight hidden md:inline-block">BMSM</span>
    </a>
  </div>

  {{--  <div class="block sm:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-red-lighter border-red-light hover:text-white hover:border-white">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>  --}}

  <div class="block flex-grow flex items-center w-auto">

    {{--  <div class="text-sm lg:flex-grow">
      <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-red-lighter hover:text-white mr-4">
        About
      </a>
    </div>  --}}

    @yield('extra-content')

    @if (false)
    <div class="">
      @auth
        <a href="{{ route('admin.streets.list') }}" class="inline-block text-sm px-3 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-red-light hover:bg-white"><i class="fas fa-toolbox mr-1"></i><span class="hidden md:inline"> Portal</span></a>
      @else
        <a href="{{ route('auth.signin') }}" class="inline-block text-sm px-3 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-red-light hover:bg-white signin"><i class="fas fa-sign-in-alt mr-1"></i> <span class="hidden md:inline"> Login</span></a>
      @endauth
    </div>
    @endif

  </div>
</nav>